version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static web app"

  build:
    commands:
      - echo "No build step required for HTML/CSS/JS"

  post_build:
    commands:
      - echo "Build phase completed successfully on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: no
